[package]
name = "yml-diff"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
colored = "3.0"

[[bin]]
name = "yml-diff"
path = "src/main.rs"